# Generated by Django 6.0.6 on 2026-07-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='signalement_image')),
                ('localisation', models.CharField(max_length=255)),
            ],
        ),
    ]
