# Generated by Django 4.2.11 on 2026-07-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalement', '0002_alter_signalement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='jour',
            field=models.DateField(auto_now=True),
        ),
    ]
