# Generated by Django 4.2.11 on 2026-07-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalement', '0003_signalement_jour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='jour',
            field=models.DateField(default='2026/07/05'),
        ),
    ]
