# Generated by Django 4.2.11 on 2026-07-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalement', '0005_alter_signalement_jour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalement',
            name='jour',
        ),
    ]
