# Generated by Django 4.2.11 on 2026-07-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalement', '0006_remove_signalement_jour'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='jour',
            field=models.DateField(auto_now=True),
        ),
    ]
