# Generated by Django 4.2.11 on 2026-07-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalement', '0007_signalement_jour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
